interface IMessages{
    checkInternetConnection:string,
    serverError:string,
    networkError:string,
    pleaseWait:string,
    validUserName:string,
    validPassword:string,
    dataClearMsg:string,
    invalidUser:string,
    invalidUserNameOrPassword:string,
    syncingPleaseWait:string,
    syncSuccessfull:string,
    getForm: string,
    warning: string,
    deleteFrom: string,
    saveSuccess:string,
    finalizedSuccess: string,
    fillAtleastOnField: string,
    autoSave: string,
    anganwadiCenter: string,
    schoolname: string,
    respondentName: string,
    womanName: string,
    errorWhileClearingFile: string,
    clearingDataPleaseWait: string
  }